---
# handlers file for CentOS-8-Nextcloud
- name: restart firewalld
  service:
    name: firewalld
    state: restarted

- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: restart php
  service:
    name: php-fpm
    state: restarted

- name: restart mariadb
  service:
    name: mariadb
    state: restarted

- name: apply new SELinux contexts
  command: 'restorecon -R {{ item }}'
  loop:
  - '/usr/share/nginx/nextcloud/'
  - '{{ data_dir }}'
